# Generated by Django 4.1 on 2022-08-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-created',)},
        ),
    ]
